/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formularios;

import conexion.ConexionBD;
import clases.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Frame;
/**
 *
 * @author win11
 */
public class frmMetasNueva extends javax.swing.JDialog {
    
    private Usuario usuarioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMetasNueva.class.getName());

    /**
     * Creates new form frmMetasNueva
     */
    public frmMetasNueva(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public frmMetasNueva(Frame parent, boolean modal, Usuario usuario){
        super(parent, modal);
        this.usuarioActual = usuario;
        initComponents();
    }
    
    public frmMetasNueva(Usuario usuario){
        this(null, true, usuario);
    }
    
    public void regresarAMetas(){
        frmMetas meta = new frmMetas(this.usuarioActual);
        meta.setLocationRelativeTo(null);
        meta.setVisible(true);
        this.dispose();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegresarMetas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreMeta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAhorroObtenido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaLimite = new javax.swing.JTextField();
        btnCrearMeta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("meta nueva");
        setBackground(new java.awt.Color(15, 23, 42));

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));

        lblRegresarMetas.setForeground(new java.awt.Color(148, 163, 184));
        lblRegresarMetas.setText("<-Regresar a metas");
        lblRegresarMetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMetasMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva meta");

        jLabel3.setBackground(new java.awt.Color(148, 163, 184));
        jLabel3.setForeground(new java.awt.Color(148, 163, 184));
        jLabel3.setText("Nombre de la meta:");

        txtNombreMeta.setBackground(new java.awt.Color(15, 23, 42));
        txtNombreMeta.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(148, 163, 184));
        jLabel4.setText("Cantidad objetivo:");

        txtCantidad.setBackground(new java.awt.Color(15, 23, 42));
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jLabel5.setForeground(new java.awt.Color(148, 163, 184));
        jLabel5.setText("Ya ahorro:");

        txtAhorroObtenido.setBackground(new java.awt.Color(15, 23, 42));
        txtAhorroObtenido.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(148, 163, 184));
        jLabel6.setText("fecha limite AAAA-MM-DD:");

        txtFechaLimite.setBackground(new java.awt.Color(15, 23, 42));
        txtFechaLimite.setForeground(new java.awt.Color(255, 255, 255));

        btnCrearMeta.setBackground(new java.awt.Color(0, 230, 118));
        btnCrearMeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearMeta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearMeta.setText("CREAR META");
        btnCrearMeta.addActionListener(this::btnCrearMetaActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(148, 163, 184));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel7.setForeground(new java.awt.Color(148, 163, 184));
        jLabel7.setText("Define una meta de ahorro personalizada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCrearMeta)
                        .addGap(72, 72, 72)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegresarMetas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreMeta)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtAhorroObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblRegresarMetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAhorroObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMeta)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void lblRegresarMetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMetasMouseClicked
        // TODO add your handling code here:
        regresarAMetas();
    }//GEN-LAST:event_lblRegresarMetasMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       regresarAMetas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMetaActionPerformed
        // TODO add your handling code here:
       String nombre = txtNombreMeta.getText().trim();
       String cantidadS = txtCantidad.getText().trim();
       String ahorroT = txtAhorroObtenido.getText().trim();
       String fechaLimite = txtFechaLimite.getText().trim();
       
       if(nombre.isEmpty() || cantidadS.isEmpty()){
           JOptionPane.showMessageDialog(this,
                   "El nombre y la cantidad son obligatorios", "campos incompletos",
                   JOptionPane.WARNING_MESSAGE);
           return;
       }
       
       double montoObjetivo;
       double montoActual = 0.0;
       
       try{
           montoObjetivo = Double.parseDouble(cantidadS);
           
           if(!ahorroT.isEmpty()){
           montoActual = Double.parseDouble(ahorroT);
       }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this,
                   "por favor ingresa numeros validos en los montos ",
                   "formato incorrecto", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       if(this.usuarioActual == null){
           JOptionPane.showMessageDialog(this, "No hay una sesion de usuario activa",
                   "erro de inicio de sesion", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       String sql = "insert into metas(id_usuario, nombre_meta, monto_objetivo, monto_actual, fecha_limite) VALUES(?,?,?,?,?)";
       
       try(Connection con = ConexionBD.getConexion();
               PreparedStatement ps = con.prepareStatement(sql)){
           ps.setInt(1, this.usuarioActual.getId());
           ps.setString(2, nombre);
           ps.setDouble(3, montoObjetivo);
           ps.setDouble(4, montoActual);
           
           if(!fechaLimite.isEmpty()){
               ps.setString(5, fechaLimite);
           }else{
               ps.setNull(5, java.sql.Types.DATE);
           }
           int filasInsertadas = ps.executeUpdate();
           
           if(filasInsertadas > 0){
               JOptionPane.showMessageDialog(this,
                       "Meta creada con exito", "Registro Guardado",
                       JOptionPane.INFORMATION_MESSAGE);
               this.dispose();
           }
       }catch(SQLException e){
           logger.log(java.util.logging.Level.SEVERE, "Error al insertar la meta", e);
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_btnCrearMetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frmMetasNueva dialog = new frmMetasNueva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearMeta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegresarMetas;
    private javax.swing.JTextField txtAhorroObtenido;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFechaLimite;
    private javax.swing.JTextField txtNombreMeta;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
