/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;
import conexion.ConexionBD;
import clases.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cedric
 */
public class frmNuevoEgreso extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private Usuario usuarioActual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmNuevoEgreso.class.getName());

    /**
     * Creates new form frmNuevoEgreso
     */
    public frmNuevoEgreso() {
        initComponents();
    }
    
    public frmNuevoEgreso(Usuario usuario){
        this.usuarioActual = usuario;
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxCategoria1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtConcepto1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        guardarEgreso = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(12, 12, 36));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo egreso");

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Registra un nuevo gasto en tu historial  ");

        btnRegresar.setBackground(new java.awt.Color(12, 12, 36));
        btnRegresar.setForeground(new java.awt.Color(204, 204, 255));
        btnRegresar.setText("<- Regresar a Egresos");
        btnRegresar.setBorder(null);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jPanel3.setBackground(new java.awt.Color(48, 49, 73));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Cantidad en MX");

        txtFecha1.setBackground(new java.awt.Color(21, 24, 47));
        txtFecha1.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha1.setBorder(null);

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Concepto (descripcion): ");

        txtCantidad1.setBackground(new java.awt.Color(21, 24, 47));
        txtCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad1.setBorder(null);

        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Categoría");

        cbxCategoria1.setBackground(new java.awt.Color(21, 24, 47));
        cbxCategoria1.setForeground(new java.awt.Color(204, 204, 255));
        cbxCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vivienda", "Alimentación", "Transporte", "Salud", "Entretenimientos", "Compras", "Educacion", "Servicios", "Otros" }));
        cbxCategoria1.setBorder(null);

        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Fecha AAAA-MM-DD");

        txtConcepto1.setBackground(new java.awt.Color(21, 24, 47));
        txtConcepto1.setForeground(new java.awt.Color(255, 255, 255));
        txtConcepto1.setBorder(null);

        jLabel9.setForeground(new java.awt.Color(204, 204, 255));

        guardarEgreso.setBackground(new java.awt.Color(30, 200, 108));
        guardarEgreso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        guardarEgreso.setForeground(new java.awt.Color(255, 255, 255));
        guardarEgreso.setText("Guardar egreso");
        guardarEgreso.setBorder(null);
        guardarEgreso.addActionListener(this::guardarEgresoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(69, 69, 94));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addGap(127, 127, 127)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cbxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(guardarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnRegresar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnRegresar)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEgresoActionPerformed
        // TODO add your handling code here:
        if(usuarioActual == null){
            JOptionPane.showMessageDialog(this, 
            "Error: No se ha identificado el usuario de la sesión.", 
            "Error de Sesión", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String cantidad = txtCantidad1.getText();
        String concepto = txtConcepto1.getText();
        String categoria = cbxCategoria1.getSelectedItem().toString();
        String fecha = txtFecha1.getText(); 
        
        //validar campos obligatorios 
        if(cantidad.isEmpty() || concepto.isEmpty()){
            JOptionPane.showMessageDialog(this, 
            "Por favor completa al menos la cantidad y el concepto.", 
            "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            double cantidadMonto = Double.parseDouble(cantidad);
            
             if(cantidadMonto <= 0){
                  JOptionPane.showMessageDialog(this, 
                "El monto debe ser mayor a 0.", 
                "Monto Inválido", JOptionPane.WARNING_MESSAGE);
            return;
             }
        
        
        //fecha actual
        java.sql.Date fechaSQL;
        if(fecha.isEmpty()){
            fechaSQL = java.sql.Date.valueOf(java.time.LocalDate.now());
        }else{
            fechaSQL = java.sql.Date.valueOf(fecha);
        }
        
        String sql = "insert into egresos (id_usuario, cantidad, concepto, categoria, fecha) VALUES (?,?, ?, ?, ?)";
        try(java.sql.Connection cn = ConexionBD.getConexion();
                 java.sql.PreparedStatement ps = cn.prepareStatement(sql)){
            ps.setInt(1, usuarioActual.getId());
            ps.setDouble(2, cantidadMonto);
            ps.setString(3, concepto);
            ps.setString(4, categoria);
            ps.setDate(5, fechaSQL);
            
            int insertando = ps.executeUpdate();
            
            if(insertando > 0){
                JOptionPane.showMessageDialog(this, 
                    "¡Egreso registrado con éxito!", 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
                frmEgresos vistaEgresos = new frmEgresos(this.usuarioActual);
                vistaEgresos.setLocationRelativeTo(null);
                vistaEgresos.setVisible(true);
                this.dispose();
            }
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(this, 
                "Error en base de datos: " + e.getMessage(), 
                "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, 
            "Formato de fecha inválido. Usa YYYY-MM-DD.", 
            "Error de Fecha", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_guardarEgresoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        frmEgresos fperl = new frmEgresos(usuarioActual);
        fperl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frmEgresos fperl = new frmEgresos(usuarioActual);
        fperl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmNuevoEgreso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxCategoria1;
    private javax.swing.JButton guardarEgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtConcepto1;
    private javax.swing.JTextField txtFecha1;
    // End of variables declaration//GEN-END:variables
}
