/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import conexion.ConexionBD;
import clases.sesionRegistro;
/**
 *
 * @author win11
 */
public class frmPerfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPerfil.class.getName());

    /**
     * Creates new form frmPerfil
     */
    public frmPerfil() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        txtNombreCompleto.setText(sesionRegistro.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        txtOcupacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIngresoMensual = new javax.swing.JTextField();
        txtAhorro = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 41, 59));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Completa tu perfil");

        jLabel2.setForeground(new java.awt.Color(148, 163, 184));
        jLabel2.setText("Personaliza tu experiencia financiera ");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\win11\\Documents\\usuario2.png")); // NOI18N

        jLabel3.setForeground(new java.awt.Color(148, 163, 184));
        jLabel3.setText("Nombre completo:");

        jLabel5.setForeground(new java.awt.Color(148, 163, 184));
        jLabel5.setText("Ocupacion:}");

        txtNombreCompleto.setBackground(new java.awt.Color(30, 41, 59));
        txtNombreCompleto.setForeground(new java.awt.Color(255, 255, 255));

        txtOcupacion.setBackground(new java.awt.Color(30, 41, 59));
        txtOcupacion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(148, 163, 184));
        jLabel6.setText("Ingreso mensual:(sin \",\" y sin \".\")");

        jLabel7.setForeground(new java.awt.Color(148, 163, 184));
        jLabel7.setText("meta de ahorro mensual:(sin \",\" y sin \".\" )");

        txtIngresoMensual.setBackground(new java.awt.Color(30, 41, 59));
        txtIngresoMensual.setForeground(new java.awt.Color(255, 255, 255));

        txtAhorro.setBackground(new java.awt.Color(30, 41, 59));
        txtAhorro.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(16, 185, 129));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR PERFIL Y CONTINUAR ->");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIngresoMensual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(txtOcupacion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAhorro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngresoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCompleto.getText().trim();
        String ocupacion = txtOcupacion.getText().trim();
        String ingresoM = txtIngresoMensual.getText().trim();
        String ahorroM = txtAhorro.getText().trim();
        
        //validar datos 
        if(nombre.isEmpty() || ocupacion.isEmpty() || ingresoM.isEmpty() || ahorroM.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "por favor completa los campos del perfil",
                    "Campos incompletos", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
        double ingreso = Double.parseDouble(ingresoM);
        double ahorro = Double.parseDouble(ahorroM);

        if (ingreso < 0 || ahorro < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ingreso y la meta deben ser cantidades mayores a 0",
                    "Monto inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Guardar en la sesión temporal
        sesionRegistro.ocupacion = ocupacion;
        sesionRegistro.ingresoMensual = ingreso;
        sesionRegistro.metaAhorro = ahorro;

        java.sql.Connection conexion = ConexionBD.getConexion();

        // 2. Insertar el nuevo usuario en MySQL (Obteniendo el ID generado)
        String sqlUsuario = "INSERT INTO usuarios (nombre, correo, contrasena, ingreso_mensual, ocupacion, meta_ahorro) VALUES (?,?,?,?,?,?)";
        java.sql.PreparedStatement pstUsuario = conexion.prepareStatement(sqlUsuario, java.sql.Statement.RETURN_GENERATED_KEYS);
        
        pstUsuario.setString(1, sesionRegistro.nombre);
        pstUsuario.setString(2, sesionRegistro.correo);
        pstUsuario.setString(3, sesionRegistro.password);
        pstUsuario.setDouble(4, ingreso);
        pstUsuario.setString(5, ocupacion);
        pstUsuario.setDouble(6, ahorro);
        pstUsuario.executeUpdate();

        // Obtener el ID del usuario recién creado
        java.sql.ResultSet rs = pstUsuario.getGeneratedKeys();
        int idUsuario = 0;
        if (rs.next()) {
            idUsuario = rs.getInt(1);
        }
        pstUsuario.close();

        // 3. Registrar automáticamente el Ingreso Inicial en la tabla 'ingresos'
        if (idUsuario > 0 && ingreso > 0) {
            String sqlIngreso = "INSERT INTO ingresos (id_usuario, cantidad, concepto, categoria, fecha) VALUES (?, ?, ?, ?, CURDATE())";
            java.sql.PreparedStatement pstIngreso = conexion.prepareStatement(sqlIngreso);
            pstIngreso.setInt(1, idUsuario);
            pstIngreso.setDouble(2, ingreso);
            pstIngreso.setString(3, "Ingreso base inicial");
            pstIngreso.setString(4, "Sueldo");
            pstIngreso.executeUpdate();
            pstIngreso.close();
        }

        javax.swing.JOptionPane.showMessageDialog(this,
                "¡Cuenta creada correctamente!\nAhora puedes iniciar sesión.",
                "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Redirigir al Login
        frmLogin login = new frmLogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Ingresa montos numéricos válidos en Ingreso y Meta de ahorro",
                "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error al guardar el usuario en la base de datos:\n" + e.getMessage(),
                "Error en la base de datos", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAhorro;
    private javax.swing.JTextField txtIngresoMensual;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtOcupacion;
    // End of variables declaration//GEN-END:variables
}
