/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.sesionRegistro;

/**
 *
 * @author win11
 */
public class frmRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegistro.class.getName());

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRegresarInicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmarPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbInicioSesion = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 41, 59));

        lblRegresarInicio.setForeground(new java.awt.Color(204, 204, 204));
        lblRegresarInicio.setText("<- Regresar al inicio");
        lblRegresarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarInicioMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(16, 185, 129));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FinanceApp");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crear Cuenta");

        jLabel4.setForeground(new java.awt.Color(148, 163, 184));
        jLabel4.setText("Comienza a gestionar tus finanzas personales hoy");

        jLabel5.setForeground(new java.awt.Color(148, 163, 184));
        jLabel5.setText("Nombre completo:");

        txtNombre.setBackground(new java.awt.Color(30, 41, 59));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(148, 163, 184));
        jLabel6.setText("correo electronico:");

        txtCorreo.setBackground(new java.awt.Color(30, 41, 59));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(148, 163, 184));
        jLabel7.setForeground(new java.awt.Color(148, 163, 184));
        jLabel7.setText("Contraseña:(min 8 max 12)");

        jLabel8.setForeground(new java.awt.Color(148, 163, 184));
        jLabel8.setText("Confirmar contraseña:");

        txtConfirmarPassword.setBackground(new java.awt.Color(30, 41, 59));
        txtConfirmarPassword.setForeground(new java.awt.Color(255, 255, 255));

        txtPassword.setBackground(new java.awt.Color(30, 41, 59));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        btnCrearCuenta.setBackground(new java.awt.Color(16, 185, 129));
        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("CREAR CUENTA");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        jLabel9.setForeground(new java.awt.Color(148, 163, 184));
        jLabel9.setText("¿Ya tienes cuenta?");

        lbInicioSesion.setForeground(new java.awt.Color(16, 185, 129));
        lbInicioSesion.setText("Iniciar Sesión");
        lbInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInicioSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInicioSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblRegresarInicio)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnCrearCuenta))
                            .addComponent(txtCorreo)
                            .addComponent(txtPassword)
                            .addComponent(txtConfirmarPassword))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRegresarInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearCuenta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbInicioSesion))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String correo = txtCorreo.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String confirmar =  String.valueOf(txtConfirmarPassword.getPassword()).trim();
        
        //validar datos 
        if(nombre.isEmpty() || correo.isEmpty() || password.isEmpty() || confirmar.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(
                    this, "por favor ingrese sus datos en los campos",
                    "campos incompletos", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validar correo
        if(!correo.contains("@") || !correo.contains(".")){
            javax.swing.JOptionPane.showMessageDialog(
            this, "ingrese un correo electronico valido.",
                    "correo invalido", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validar contraseña
        if(password.length()< 8){
            javax.swing.JOptionPane.showMessageDialog(this, 
            "La contraseña debe tener al menos 8 caracteres.", 
            "Contraseña muy corta", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
            
        }
        
        //confirmar contraseña 
        if(!password.equals(confirmar)){
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Las contraseñas no coinciden. Inténtalo de nuevo.", 
            "Error de validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //guardar datos temporales 
        sesionRegistro.nombre = nombre;
        sesionRegistro.correo = correo;
        sesionRegistro.password = password;
        
        //pasar al formulario de perfil 
        frmPerfil perfil = new frmPerfil();
        perfil.setLocationRelativeTo(null);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void lblRegresarInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarInicioMouseClicked
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblRegresarInicioMouseClicked

    private void lbInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInicioSesionMouseClicked
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lbInicioSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbInicioSesion;
    private javax.swing.JLabel lblRegresarInicio;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
